name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build
      run: npm run build
      
    - name: Test build output
      run: |
        # Verificar que el build se creó correctamente
        if [ ! -d "dist" ]; then
          echo "❌ Build directory not found"
          exit 1
        fi
        
        # Verificar que index.html existe
        if [ ! -f "dist/index.html" ]; then
          echo "❌ index.html not found in build"
          exit 1
        fi
        
        echo "✅ Build verification passed" 